'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiUrl } from '@/utils/api';
import { BadgeDollarSign, FileText, Receipt, ShieldCheck } from 'lucide-react';

type PayoutRecord = {
  id: number;
  submission: number;
  submission_title: string;
  submission_code?: string;
  invoice_number: string;
  amount_bdt: number | string;
  status: string;
  payment_method: string;
  payment_reference?: string | null;
  notes?: string | null;
  generated_by_name?: string | null;
  created_at: string;
  paid_at?: string | null;
};

export default function ReviewerPaymentsTab() {
  const [payments, setPayments] = useState<PayoutRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const token = localStorage.getItem('access_token');

    if (!token) {
      setError('Please sign in again to view your payment history.');
      setLoading(false);
      return;
    }

    const loadPayments = async () => {
      try {
        setLoading(true);
        setError('');

        const res = await fetch(apiUrl('reviewer/payments/history/'), {
          headers: { Authorization: `Bearer ${token}` },
        });

        const data = await res.json().catch(() => null);
        if (!res.ok) {
          throw new Error(data?.detail || `Unable to load payment history (${res.status})`);
        }

        setPayments(Array.isArray(data) ? data : data?.results || []);
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : 'Failed to load payment history.';
        setError(message);
      } finally {
        setLoading(false);
      }
    };

    loadPayments();
  }, []);

  const totalReceived = useMemo(
    () => payments.reduce((sum, item) => sum + Number(item.amount_bdt || 0), 0),
    [payments],
  );

  return (
    <div className="space-y-8">
      <div>
        <h3 className="text-3xl font-bold text-gray-900">Received Payments</h3>
        <p className="text-gray-600 mt-2">Track all reviewer payouts and invoice records linked to your review work.</p>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <article className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 shadow-sm">
          <div className="flex items-center gap-3 text-emerald-700">
            <BadgeDollarSign size={18} />
            <span className="text-sm font-semibold uppercase tracking-wide">Total received</span>
          </div>
          <p className="text-3xl font-extrabold text-emerald-900 mt-3">BDT {totalReceived.toLocaleString()}</p>
        </article>

        <article className="rounded-2xl border border-blue-100 bg-blue-50 p-5 shadow-sm">
          <div className="flex items-center gap-3 text-blue-700">
            <Receipt size={18} />
            <span className="text-sm font-semibold uppercase tracking-wide">Invoice records</span>
          </div>
          <p className="text-3xl font-extrabold text-blue-900 mt-3">{payments.length}</p>
        </article>

        <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
          <div className="flex items-center gap-3 text-slate-700">
            <ShieldCheck size={18} />
            <span className="text-sm font-semibold uppercase tracking-wide">Latest status</span>
          </div>
          <p className="text-lg font-semibold text-slate-900 mt-3">
            {payments.length > 0 ? payments[0].status.replace(/_/g, ' ') : 'No payout yet'}
          </p>
        </article>
      </div>

      <section className="rounded-2xl border bg-white shadow-sm p-6">
        <div className="flex items-center justify-between gap-3 mb-4">
          <div>
            <h4 className="text-xl font-semibold text-gray-900">Payment history</h4>
            <p className="text-sm text-gray-600">Each entry includes the manuscript, invoice number, payment status, and method used.</p>
          </div>
          <div className="hidden sm:flex items-center gap-2 rounded-xl bg-gray-100 px-3 py-2 text-sm text-gray-700">
            <FileText size={16} />
            {payments.length} record(s)
          </div>
        </div>

        {loading ? (
          <div className="text-gray-600 py-6 text-center">Loading your received payments...</div>
        ) : error ? (
          <div className="bg-red-50 border border-red-200 text-red-800 p-4 rounded-xl">{error}</div>
        ) : payments.length === 0 ? (
          <div className="rounded-xl border border-dashed border-gray-200 bg-gray-50 p-8 text-center text-gray-600">
            No payment records found yet. Payments generated by editors/admins will appear here automatically.
          </div>
        ) : (
          <div className="space-y-4">
            {payments.map((item) => (
              <article key={item.id} className="rounded-2xl border border-gray-200 bg-gray-50 p-5">
                <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4">
                  <div className="space-y-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="text-xs uppercase tracking-[0.18em] text-blue-700">Invoice {item.invoice_number}</span>
                      <span className="px-2 py-1 rounded-full bg-white border text-xs font-semibold text-gray-700">{item.status.replace(/_/g, ' ')}</span>
                    </div>
                    <h5 className="text-lg font-semibold text-gray-900">{item.submission_title || 'Manuscript review payment'}</h5>
                    <p className="text-sm text-gray-600">Manuscript ID: {item.submission_code || `RRIJ_${item.submission}` || '—'} • Method: {item.payment_method || '—'}</p>
                    {item.notes ? <p className="text-sm text-gray-600">Note: {item.notes}</p> : null}
                    {item.generated_by_name ? <p className="text-xs text-gray-500">Generated by: {item.generated_by_name}</p> : null}
                  </div>

                  <div className="lg:text-right space-y-1 text-sm text-gray-700">
                    <p className="text-2xl font-extrabold text-gray-900">BDT {Number(item.amount_bdt || 0).toLocaleString()}</p>
                    <p>Created: {new Date(item.created_at).toLocaleString()}</p>
                    <p>Paid at: {item.paid_at ? new Date(item.paid_at).toLocaleString() : 'Pending'}</p>
                    {item.payment_reference ? <p>Reference: {item.payment_reference}</p> : null}
                  </div>
                </div>
              </article>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
