# Generated by Django 6.0.1 on 2026-02-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_affiliation_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=255)),
                ('expertise', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='editorial_photos/')),
                ('role_type', models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('managing_editor', 'Managing Editor'), ('associate_editor', 'Associate Editor'), ('advisory_board', 'Advisory Board Member'), ('other', 'Other')], default='other', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Editorial Board Member',
                'verbose_name_plural': 'Editorial Board Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
