# Generated by Django 6.0.1 on 2026-02-12 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_editorialboardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('manuscript_type', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='submissions/')),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='authored_submissions', to=settings.AUTH_USER_MODEL)),
                ('corresponding_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corresponding_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
