# Generated by Django 6.0.1 on 2026-02-24 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_issue_volume_paper_issue_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='assigned', max_length=50)),
                ('review_report', models.FileField(blank=True, null=True, upload_to='review_reports/')),
                ('reviewer_remarks', models.TextField(blank=True, null=True)),
                ('reviewer_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.paper')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role__name': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('paper', 'reviewer')},
            },
        ),
    ]
