# Generated by Django 6.0.1 on 2026-02-25 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reviewerassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='assigned', max_length=50)),
                ('review_report', models.FileField(blank=True, null=True, upload_to='review_reports/')),
                ('reviewer_remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role__name__in': ['reviewer', 'editorial_board']}, on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='core.submission')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('submission', 'assigned_to')},
            },
        ),
        migrations.DeleteModel(
            name='ReviewerAssignment',
        ),
    ]
