# Generated by Django 6.0.1 on 2026-02-27 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reviewassignment_delete_reviewerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='current_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('desk_review', 'Desk Review'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='decision_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='desk_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='desk_review_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='desk_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed Initial Screening'), ('desk_rejected', 'Desk Rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='editor_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='editor_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='final_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='core.submission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
