# Generated by Django 6.0.1 on 2026-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_submission_current_status_submission_decision_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardmember',
            name='role_type',
            field=models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('executive_editor', 'Executive Editor'), ('managing_editor', 'Managing Editor'), ('associate_editor', 'Associate Editor'), ('member', 'Member'), ('reviewers_panel', 'Reviewers Panel'), ('advisory_board', 'Advisory Board Member'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
