# Generated by Django 6.0.1 on 2026-02-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_editorialboardmember_role_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
