# Generated by Django 6.0.1 on 2026-03-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='acknowledgement',
            field=models.TextField(blank=True, help_text='Acknowledgements, funding sources, etc.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='conflict_of_interest',
            field=models.TextField(blank=True, help_text='Declare any conflicts of interest', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='manual_authors',
            field=models.TextField(blank=True, help_text='Comma-separated names of additional/manual authors (if not registered users)', null=True),
        ),
    ]
