# Generated by Django 6.0.1 on 2026-03-07 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_submission_acknowledgement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(help_text='Final date and time for new manuscript submissions')),
                ('extended_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Reason for extension (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission Deadline',
                'verbose_name_plural': 'Submission Deadlines',
                'ordering': ['-deadline'],
            },
        ),
    ]
