# Generated by Django 6.0.1 on 2026-03-09 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_submissiondeadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.TextField(help_text='Your main fields of expertise')),
                ('affiliation', models.CharField(help_text='Current institution/organization', max_length=255)),
                ('publications', models.TextField(blank=True, help_text='Key publications (last 5–10 years)')),
                ('cv', models.FileField(help_text='Upload your CV (PDF preferred)', upload_to='reviewer_cvs/')),
                ('availability', models.CharField(help_text='How many reviews can you handle per year?', max_length=50)),
                ('interests', models.TextField(blank=True, help_text='Research interests / keywords')),
                ('orcid', models.CharField(blank=True, help_text='ORCID iD', max_length=50)),
                ('google_scholar', models.URLField(blank=True, help_text='Google Scholar profile URL')),
                ('motivation', models.TextField(help_text='Why do you want to review for RRI Journal?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviewer Application',
                'verbose_name_plural': 'Reviewer Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
