# Generated by Django 6.0.1 on 2026-03-09 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reviewerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
