# Generated by Django 6.0.1 on 2026-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_reviewerapplication_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerapplication',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for guest applicants', max_length=254),
        ),
        migrations.AddField(
            model_name='reviewerapplication',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name for guest applicants', max_length=255),
        ),
    ]
