# Generated by Cursor on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_reviewerapplication_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewassignment",
            name="invite_response",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                default="pending",
                help_text="Reviewer response to the invitation email (accept/reject).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="invitation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="invite_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="invite_rejection_reasons",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="invite_rejection_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]

