# Generated by Django 6.0.1 on 2026-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reviewassignment_invite_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='comment_to_author',
            field=models.TextField(blank=True, help_text='Comments visible to the author', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='comment_to_editor',
            field=models.TextField(blank=True, help_text='Comments visible to the editor/admin', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='recommendation',
            field=models.CharField(choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', help_text="Reviewer's recommendation for the manuscript", max_length=50),
        ),
    ]
