# Generated by Django 6.0.1 on 2026-03-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero slide image.', upload_to='hero_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text.', max_length=255)),
                ('link_url', models.URLField(blank=True, help_text='Optional URL to open when clicking the slide.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If inactive, it will not appear in the homepage carousel.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_images_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
