# Generated by Django 6.0.1 on 2026-03-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_guidelinedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidelinedocument',
            name='rendered_pdf',
            field=models.FileField(blank=True, help_text='Converted PDF used for faithful rendering of DOCX uploads.', null=True, upload_to='guidelines/rendered/'),
        ),
    ]
