# Generated by Django 6.0.1 on 2026-03-31 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_guidelinedocument_rendered_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bdt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_enabled', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_set', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_fee', to='core.submission')),
            ],
            options={
                'ordering': ['-set_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('invalid', 'Invalid')], default='initiated', max_length=20)),
                ('tran_id', models.CharField(max_length=100, unique=True)),
                ('sessionkey', models.CharField(blank=True, default='', max_length=255)),
                ('val_id', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_page_url', models.URLField(blank=True, default='')),
                ('bank_tran_id', models.CharField(blank=True, default='', max_length=255)),
                ('card_type', models.CharField(blank=True, default='', max_length=100)),
                ('card_brand', models.CharField(blank=True, default='', max_length=100)),
                ('card_issuer', models.CharField(blank=True, default='', max_length=255)),
                ('risk_level', models.CharField(blank=True, default='', max_length=50)),
                ('risk_title', models.CharField(blank=True, default='', max_length=255)),
                ('raw_init_payload', models.JSONField(blank=True, null=True)),
                ('raw_callback_payload', models.JSONField(blank=True, null=True)),
                ('raw_validation_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.submission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', 'status'], name='core_paymen_submiss_cfc068_idx'), models.Index(fields=['payer', 'status'], name='core_paymen_payer_i_d2837c_idx')],
            },
        ),
    ]
