# Generated by Django 6.0.1 on 2026-04-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_importantdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, max_length=500, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_scans', to='core.paper')),
            ],
        ),
    ]
