# Generated by Django 6.0.1 on 2026-04-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_plagiarismscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiarismscan',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_scans', to='core.paper'),
        ),
    ]
