# Generated by Django 6.0.1 on 2026-04-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_plagiarismscan_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='plagiarism_report',
            field=models.FileField(blank=True, null=True, upload_to='review_reports/'),
        ),
    ]
