# Generated by Django 6.0.1 on 2026-04-19 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_reviewassignment_plagiarism_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallForPaperAdvertize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload a PDF or image file for the advertisement.', upload_to='call_for_paper_ads/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], default='pdf', help_text='Type of file uploaded.', max_length=10)),
                ('title', models.CharField(blank=True, help_text='Optional title/name for this advertisement.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this advertisement.')),
                ('is_active', models.BooleanField(default=True, help_text='If inactive, the advertisement will not be displayed.')),
                ('inactive_after', models.DateTimeField(blank=True, help_text='If set, the advertisement will automatically become inactive after this date/time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_for_paper_ads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call for Paper Advertisement',
                'verbose_name_plural': 'Call for Paper Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
