# Generated by Django 6.0.1 on 2026-04-22 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_callforpaperadvertize'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for this submission period', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the call for papers')),
                ('start_date', models.DateTimeField(help_text='When submissions open for this period')),
                ('end_date', models.DateTimeField(help_text='When submissions close for this period')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this submission period is currently active')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active period (only one can be current)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_periods_created', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_periods', to='core.issue')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_periods', to='core.volume')),
            ],
            options={
                'verbose_name': 'Submission Period',
                'verbose_name_plural': 'Submission Periods',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('issue__isnull', False)), fields=('volume', 'issue'), name='unique_volume_issue_period'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_after_start_date')],
            },
        ),
    ]
