# Generated by Django 6.0.1 on 2026-04-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_submissionperiod'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submissionperiod',
            name='unique_volume_issue_period',
        ),
        migrations.AlterField(
            model_name='submissionperiod',
            name='issue',
            field=models.CharField(blank=True, help_text="Issue name or number (e.g., 'Issue 1', 'Special Issue')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submissionperiod',
            name='volume',
            field=models.CharField(blank=True, help_text="Volume name or number (e.g., 'Volume 1', 'Vol 2024')", max_length=255, null=True),
        ),
    ]
