# Generated by Django 6.0.1 on 2026-04-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_submissionperiod_unique_volume_issue_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='additional_references',
            field=models.TextField(blank=True, help_text='Additional reference suggestions', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='alternative_title',
            field=models.TextField(blank=True, help_text='Alternative title suggestion if current title is not suitable', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='are_references_sufficient',
            field=models.BooleanField(blank=True, help_text='Are the references sufficient and recent?', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='is_abstract_comprehensive',
            field=models.BooleanField(blank=True, help_text='Is the abstract of the article comprehensive?', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='is_important_for_scientific_community',
            field=models.BooleanField(blank=True, help_text='Is the manuscript important for scientific community?', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='is_intro_conclusion_sufficient',
            field=models.BooleanField(blank=True, help_text='Do the author(s) provide a sufficient overview in the introduction and conclusion?', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='is_language_quality_suitable',
            field=models.BooleanField(blank=True, help_text='Is language/English quality of the article suitable for scholarly communications?', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='is_structure_appropriate',
            field=models.BooleanField(blank=True, help_text='Are subsections and structure of the manuscript appropriate?', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='is_title_suitable',
            field=models.BooleanField(blank=True, help_text='Is the title of the article suitable?', null=True),
        ),
    ]
