# Generated by Django 6.0.1 on 2026-04-27 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_reviewassignment_additional_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='feedback_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the feedback was sent to the author', null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='feedback_sent_by',
            field=models.ForeignKey(blank=True, help_text='Admin/editor who sent the feedback to author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_sent_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='feedback_sent_to_author',
            field=models.BooleanField(default=False, help_text='Whether the review feedback has been sent to the author'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer_feedback',
            field=models.JSONField(blank=True, default=list, help_text='List of reviewer feedback sent to author, each containing reviewer name, feedback, and checklist'),
        ),
    ]
