# Generated by Django 6.0.1 on 2026-04-29 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_reviewassignment_feedback_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision'), ('history', 'History'), ('scope_topics', 'Scope & Topics'), ('key_facts', 'Key Facts'), ('editorial_team', 'Editorial Team')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Main content text for the section')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topics (used for Scope & Topics section)')),
                ('is_active', models.BooleanField(default=True, help_text="If inactive, section won't appear on the page")),
                ('sort_order', models.IntegerField(default=0, help_text='Order of sections on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_contents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'section'],
            },
        ),
    ]
