# Generated by Django 6.0.1 on 2026-05-16 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_aboutpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptFormatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='manuscript_formats/')),
                ('rendered_pdf', models.FileField(blank=True, help_text='Converted PDF used for faithful rendering of DOCX uploads.', null=True, upload_to='manuscript_formats/rendered/')),
                ('file_extension', models.CharField(blank=True, default='', max_length=20)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('extraction_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuscript_formats_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
