# Generated by Django 6.0.1 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_manuscriptformatdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='originality_declaration',
            field=models.BooleanField(default=False, help_text='I confirm that this manuscript is original, has not been previously published, is not currently under consideration elsewhere, and that all authors have approved this submission.'),
        ),
    ]
