# Generated by Django 6.0.1 on 2026-05-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_submission_originality_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerapplication',
            name='motivation',
            field=models.TextField(help_text='Why do you want to review for Technical Journal?'),
        ),
    ]
