# Generated by Django 6.0.1 on 2026-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_reviewerapplication_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='current_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('desk_review', 'Desk Review'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('ready_for_publication', 'Ready for Publication'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
