# Generated by Django 6.0.1 on 2026-06-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_submission_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_code',
            field=models.CharField(blank=True, help_text='Unique manuscript code like RRIJ_2026_18(1)_01', max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_period',
            field=models.ForeignKey(blank=True, help_text='Submission period that this manuscript belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.submissionperiod'),
        ),
    ]
