# Generated by Django 6.0.1 on 2026-06-05 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_submission_submission_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='revision_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision_extension_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_revision_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision_extension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision_extension_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision_extension_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved')], default='none', max_length=30),
        ),
    ]
