# Generated by Django 6.0.1 on 2026-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_user_payment_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewassignment',
            name='invite_response',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', help_text='Reviewer response to the invitation email (accept/reject/withdraw).', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='assigned', max_length=50),
        ),
    ]
